# Generated by Django 6.0.2 on 2026-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_discoutn_offer_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='float',
            new_name='price',
        ),
    ]
